version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_DATABASE
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3307:3306
  app:
    depends_on:
      - mysqldb
    image: docker-app
    build: .
    env_file: ./.env
    ports:
      - 6868:8080
    environment:
      SPRING_APPLICTION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQL_DATABASE?serverTimezone=Europe/Kiev"
        "spring.datasource.username" : "$MYSQLDB_USER"
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD"
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect"
        "spring.jpa.hibernate.ddl-auto=" : "create"
        "spring.jpa.show-sql" : "true"
      }'